# Generated by Django 5.0.2 on 2024-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name": "Amenity", "verbose_name_plural": "Amenities"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Room", "verbose_name_plural": "Rooms"},
        ),
        migrations.AlterModelOptions(
            name="roomstandard",
            options={
                "verbose_name": "Room Standard",
                "verbose_name_plural": "Room Standards",
            },
        ),
        migrations.AlterField(
            model_name="roomstandard",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="room_standards", to="rooms.amenity"
            ),
        ),
    ]
