version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: .
    image: website
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code
