# Generated by Django 5.0.2 on 2024-03-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
