# Generated by Django 5.0.2 on 2024-03-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("employees", "0002_alter_employee_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="employee_groups",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employee_permissions",
        ),
        migrations.AlterField(
            model_name="employee",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="auth.group"
            ),
        ),
        migrations.DeleteModel(
            name="CustomGroup",
        ),
        migrations.DeleteModel(
            name="CustomPermission",
        ),
    ]
